sliders = GAMMA_CORRECTION SH_FL SH_DY SH_FL_R SH_FL_G SH_FL_B SH_DY_R SH_DY_G SH_DY_B FX_WT_A FX_WT_B OW_BL_R OW_BL_G OW_BL_B OW_SL_R OW_SL_G OW_SL_B OW_ML_R OW_ML_G OW_ML_B OW_WL_R OW_WL_G OW_WL_B FX_PT_A FX_PT_B NT_BL_R NT_BL_G NT_BL_B NT_WL_R NT_WL_G NT_WL_B ND_VD_DN ND_VD_HG ND_VD_DP ND_BL_R ND_BL_G ND_BL_B ND_WL_R ND_WL_G ND_WL_B FG_OW_R FG_OW_G FG_OW_B FG_OW_LIG FG_OW_MIX FG_OW_RAD_B FG_OW_DEP_B FG_OW_EXP FG_OW_RAD_C FG_OW_DEP_C FG_OW_RAD_P FG_OW_DEP_P
separateAo = false
oldLighting = false

screen.columns = 1
screen = <empty> [LIGHT] [FOG] [SHADOWS] [EFFECTS] [MISC]

screen.LIGHT.columns = 3
screen.LIGHT = [LIGHT_OW_] [LIGHT_NT_] [LIGHT_ND_]

screen.FOG.columns = 2
screen.FOG = [FOG_OW] [FOG_WTH] [FOG_NT] [FOG_SUB] [FOG_ND] [FOG_BLI]

screen.FOG_OW.columns = 3
screen.FOG_OW = FG_OW_R FG_OW_G FG_OW_B FG_OW_SKY FG_OW_LIG FG_OW_MIX FG_OW_RAD_B FG_OW_DEP_B FG_OW_EXP FG_OW_RAD_C FG_OW_DEP_C FG_OW_EXO FG_OW_RAD_P FG_OW_DEP_P

screen.SHADOWS.columns = 3
screen.SHADOWS = SH_FL SH_DY <empty> SH_FL_R SH_FL_G SH_FL_B SH_DY_R SH_DY_G SH_DY_B

screen.EFFECTS = FX_WT_A FX_PT_A FX_WT_B FX_PT_B

screen.MISC = GAMMA_CORRECTION BLOCKFACE_SHADING SPAWN_HIGHLIGHT

